# Generated by Django 3.2.2 on 2021-05-07 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('postcounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allcounts',
            name='all_count',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='all_count', to='postcounts.postcount'),
        ),
    ]
